### ISSUE TITLE
도메인 패키지 구조

### ISSUE THREAD

**Issue by proceane** [RidingMate/RidingMate-BackEnd#13]
현재 domain 패키지 안에 aggregate, repository, value가 있는 구조로 되어있는데
도메인별로 패키지를 구분하는 건 어떨까요?
예를 들면 domain > user > aggregate, repository, value로 구분

**Comment by kaaang** [comment]
아 user는 user하위로 몰아두고 그런식으로요?!?!

**Comment by proceane** [comment]
네넹! 각 도메인 하위에 도메인 관련 클래스들을 다 넣으면 나중에 찾기 좋을거같아요!

**Comment by proceane** [comment]
처음에 말했던 건 도메인 하위에 패키지로 구분한다는 내용이었는데

**Comment by proceane** [comment]
일단 도메인별로 패키지 구분해서 파일 옮겨놨어여 
이 구조가 불편해지면 논의해서 바꿔용!

**Comment by kaaang** [comment]
넵 확인했습니당!
