### ISSUE TITLE
도메인 패키지 관련 질문

### ISSUE THREAD

**Issue by kaaang** [RidingMate/RidingMate-BackEnd#16]
패키지 구조 상에서 jpa 하위 카테고리 같은 경우는 같은 패키지에 진행하면 될까요???

**Comment by proceane** [comment]
infra.persist.jpa 패키지 안에 entity랑 repository 패키지를 만들어놨는데 그 구조가 확정된 건 아니에요

**Comment by kaaang** [comment]
그러면 그냥 따로 패키지 안나누고 같은 패키지에 작업해두겠슴당!
