### ISSUE TITLE
Oiling 도메인 작성 관련

### ISSUE THREAD

**Issue by kaaang** [RidingMate/RidingMate-BackEnd#20]
bike 관련 하위에 작성 했는데 혹시 어떠신가요? 별로면 밖으로 빼곘습니다. 바운디드가 안에 속해있어서 약간 표현 느낌으로 해봤는데 함 확인하시고 답변 부탁드립니다!

**Comment by proceane** [comment]
oiling이 아직 bike 외에는 안 쓸 것 같긴한데 결국은 별개의 도메인이라 따로 빼는 게 괜찮을거 같다고 생각해요
oiling이 bike의 값객체면 bike 패키지에 놔둬도 상관없을거같은데 엔티티라서..

**Comment by proceane** [comment]
fuel에 한표..

**Comment by kaaang** [comment]
패키지 구조는 이해했습니다!
이름 변경은 수욜까지 맞춰둘게요,,, ㅋㅋㅋㅋㅋㅋㅋㅋ
